#!/usr/bin/env bash
# =============================================================================
# Audient iD14 Linux Mint / PipeWire setup script
# Fixes: mono left-channel-only output, surround misdetection, volume control
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log()    { echo -e "${GREEN}[✓]${NC} $1"; }
warn()   { echo -e "${YELLOW}[!]${NC} $1"; }
error()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }
section(){ echo -e "\n${YELLOW}--- $1 ---${NC}"; }

# =============================================================================
# 1. Detect the iD14
# =============================================================================
section "Detecting Audient iD14"

SINK_NAME=$(pactl list sinks short | grep -i 'iD14' | awk '{print $2}')
CARD_NUM=$(aplay -l | grep 'iD14' | sed 's/:.*$//g' | sed 's/card //')

if [ -z "$SINK_NAME" ]; then
    error "Audient iD14 not found. Make sure it is plugged in and recognised by the system."
fi

if [ -z "$CARD_NUM" ]; then
    error "Could not determine ALSA card number for iD14."
fi

log "Found sink:    $SINK_NAME"
log "ALSA card num: $CARD_NUM"

# =============================================================================
# 2. Fix ALSA Speaker balance (pins both channels to 100% at hardware layer)
# =============================================================================
section "Fixing ALSA Speaker balance"

amixer -c "$CARD_NUM" sset 'Speaker' 100% \
    && log "Speaker balance set to 100% on both channels." \
    || warn "Could not set Speaker balance — control may not exist on this firmware version."

# =============================================================================
# 3. Write PipeWire virtual stereo sink config
# =============================================================================
section "Writing PipeWire virtual stereo sink config"

PIPEWIRE_CONF_DIR="$HOME/.config/pipewire/pipewire.conf.d"
PIPEWIRE_CONF="$PIPEWIRE_CONF_DIR/id14.conf"

mkdir -p "$PIPEWIRE_CONF_DIR"

cat > "$PIPEWIRE_CONF" << EOF
# ~/.config/pipewire/pipewire.conf.d/id14.conf
# Auto-generated by audient-id14-setup.sh
# Maps the iD14's misdetected surround sink into a clean stereo virtual device.

context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Audient iD14 Stereo"
            capture.props = {
                node.name = "iD14_Stereo"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name = "playback.iD14_Stereo"
                audio.position = [ FL FR ]
                target.object = "$SINK_NAME"
                stream.dont-remix = true
                node.passive = true
                priority.driver = 2000
                priority.session = 2000
            }
        }
    }
]
EOF

log "PipeWire config written to $PIPEWIRE_CONF"

# =============================================================================
# 4. Restart PipeWire
# =============================================================================
section "Restarting PipeWire"

systemctl --user restart pipewire.service pipewire-pulse.service
sleep 2
log "PipeWire restarted."

# =============================================================================
# 5. Set virtual sink as default
# =============================================================================
section "Setting iD14 Stereo as default sink"

# Wait briefly for the virtual sink to register
sleep 1
pactl set-default-sink iD14_Stereo \
    && log "Default sink set to iD14_Stereo." \
    || warn "Could not set default sink — virtual device may not have appeared yet. Try running: pactl set-default-sink iD14_Stereo"

# =============================================================================
# 6. Install the login startup fix script
# =============================================================================
section "Installing startup fix script"

STARTUP_SCRIPT="$HOME/.local/bin/id14-channel-fix.sh"
mkdir -p "$HOME/.local/bin"

cat > "$STARTUP_SCRIPT" << 'STARTUP'
#!/usr/bin/env bash
# Audient iD14 login fix — run at startup
# Resets ALSA balance and ensures virtual sink is default

sleep 3  # give PipeWire time to initialise

card=$(aplay -l | grep 'iD14' | sed 's/:.*$//g' | sed 's/card //')
if [ -n "$card" ]; then
    amixer -c "$card" sset 'Speaker' 100%
fi

pactl set-default-sink iD14_Stereo
STARTUP

chmod +x "$STARTUP_SCRIPT"
log "Startup script written to $STARTUP_SCRIPT"

# =============================================================================
# 7. Register startup script with XDG autostart (works on all DEs)
# =============================================================================
section "Registering with XDG autostart"

AUTOSTART_DIR="$HOME/.config/autostart"
AUTOSTART_FILE="$AUTOSTART_DIR/id14-channel-fix.desktop"
mkdir -p "$AUTOSTART_DIR"

cat > "$AUTOSTART_FILE" << EOF
[Desktop Entry]
Type=Application
Name=Audient iD14 Fix
Comment=Fixes ALSA balance and PipeWire default sink for Audient iD14
Exec=$STARTUP_SCRIPT
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
EOF

log "Autostart entry written to $AUTOSTART_FILE"

# =============================================================================
# Done
# =============================================================================
section "All done"
echo ""
echo "  What was configured:"
echo "  • ALSA 'Speaker' balance pinned to 100% (hardware layer)"
echo "  • PipeWire virtual stereo sink 'iD14_Stereo' created"
echo "  • iD14_Stereo set as default audio output"
echo "  • Startup script installed at $STARTUP_SCRIPT"
echo "  • XDG autostart entry registered (runs on every login)"
echo ""
echo "  Your keyboard volume keys and tray volume now control the PipeWire"
echo "  virtual sink, while the ALSA hardware layer stays pinned at 100%."
echo ""
warn "If you don't hear audio: open sound settings and manually select 'Audient iD14 Stereo'."
warn "If the virtual device isn't visible in your tray: right-click the audio icon → Show virtual devices."